### ISSUE TITLE
Removing xlarge landscape

### ISSUE THREAD

**Issue by miladesign** [Anrimian/music-player#106]
Hi. thanks for this amazing app.
i want to remove xlarge landscape resources and use landscape only. but when i remove xlarge resources i cant build this project.
can you help me please

**Comment by Anrimian** [comment]
Could you tell which files you removed and which error you got?

**Comment by miladesign** [comment]
i removed layout-xlarge-land folder from resources. then in got errors in PlayerFragment.java file for `panelBinding = viewBinding.clMusicPanel` not found.

**Comment by Anrimian** [comment]
Layouts on the main activity had been writing in a different times and are a little complex. Yep, there is a mess with layouts. It requires a little refactoring and ids ordering. I don't have any advices for now.

**Comment by miladesign** [comment]
Thanks. so i guess i most do it myself :D
Also if you can add 2 more options it will be good.
1. Auto play music when app start
2. Auto run app when android restart/start
That will be very good for cars android monitors

**Comment by Anrimian** [comment]
I guess it will be low-priority one, only if except I get more requests about it.
