### ISSUE TITLE
Playback notification times out quickly during pause

### ISSUE THREAD

**Issue by Harvie** [Anrimian/music-player#171]
I play music using bt headset. Press pause button on that. Can unpause it as well, but only for short amount of time. Shortly after being paused, the notification times out and when i try to unpause few minutes later using bt headset, the android no longer knows what to unpause, since there is no playback announced by the app.

Obviously i can unpause in the app, but that means pulling phone from pocket and unlocking it.

Please make this timeout configurable.

**Comment by Anrimian** [comment]
It's connected not with notification, but with media session. In the version 0.9.5 it's changed, soon it will start deploying in production. Will see how it will work.

**Comment by Harvie** [comment]
> It's connected not with notification, but with media session.

Quite possible. But i've noticed the notification disappears at about the same time when the unpause via bluetooth stops working.

**Comment by Anrimian** [comment]
Version 0.9.5 is published, check it out.
Expected behavior: after pause notification will  disappear after some time(before android 11), but playback should be resumable by play command from headset.

**Comment by Anrimian** [comment]
I'll leave link to this [issue](https://github.com/Anrimian/music-player/issues/66) if it won't help

**Comment by Anrimian** [comment]
In version 0.9.7 was added the possibility to keep notification for a certain time.
