### ISSUE TITLE
Can't build project in Android Studio

### ISSUE THREAD

**Issue by nofishonfriday** [Anrimian/music-player#197]
Hi,

I'm trying to build your project (thanks for making it open source), but I get quite a few errors.
I'm using latest Android Studio (Electric Eel | 2022.1.1 Patch 1, current latest commit on your `master` branch, b27ec9bf64b376b661b3ffe5e90fbb538a887ab3).

Could you tell me what's wrong?
Thanks for help.

![build errors](https://user-images.githubusercontent.com/7658194/220431100-cb53e018-5bd5-4ab5-aa18-7b25d6dfc166.jpg)

(I'm usually a desktop dev, see my GitHub profile if you like, trying to get into Android development and your project looks interesting, that's why I'm trying to build it for learning purpose. :))

**Comment by Anrimian** [comment]
Likely I forgot to copy some classes in this repo.

**Comment by nofishonfriday** [comment]
Thanks for the reply.
Indeed I can't find for example a `ExcludeReason` class.
Would you add the missing source files to the repo to make it buildable? That would be nice. :)

**Comment by Anrimian** [comment]
Have pushed an update, check it out.

**Comment by nofishonfriday** [comment]
Sorry for late reply (was travelling), it builds fine now. Issue can be closed.
Thank you!
