### ISSUE TITLE
Consider to not use completely compressed cover for notification

### ISSUE THREAD

**Issue by mariocynicys** [Anrimian/music-player#201]
The cover art is pixelated in the lock screen notification. This happens with all audio tracks, but some are more apparent than others.
Here is an example:
![Screenshot_20230309-210809_Music Player](https://user-images.githubusercontent.com/56920956/224129836-18e04be1-6ced-4aac-a711-cd391c5f9178.png)

I am running Android 13 if that makes any difference. But this used to happen in Android 12 as well. Running Pixel Experience.

**Comment by Anrimian** [comment]
Option: consider using different compressing option, for notification image size can be up to 800Kb.

**Comment by Anrimian** [comment]
Implemented for android 13+ in version 0.9.7, for pre-13 android it's compressed by system.
