### ISSUE TITLE
Covers&buttons shape

### ISSUE THREAD

**Issue by Anrimian** [Anrimian/music-player#220]
Round or rounded rectangle.
Make them configurable manually in themes, ~~with possibility to follow system values.~~

**Comment by unseenlarks** [comment]
would this apply to the 'play' button next to each track? would be a great addition to resize or even hide, as now playing song is indicated by colour change, and just tapping anywhere starts playback, so the button is not essential but nice to have for personalisation.

am enjoying using this app, looked up the repo to leave a comment and a thank you. :)

**Comment by Anrimian** [comment]
Let's not overcomplicate for now.
Implemented in version 0.9.8
