### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Lucky390163** [Anrimian/music-player#233]
1) Please add the newly  added songs tab.Ut will make my work easier.
2) Please add an option to show lyrics, e.g, synced type.
3) Please also add an option to choose or change albumart ratio like square or without rounds completely without edges.

**Comment by Anrimian** [comment]
1. Already exists, composition screen with sorting type
2. This issue already exists: https://github.com/Anrimian/music-player/issues/214
3. This issue already exists: https://github.com/Anrimian/music-player/issues/118
